/* `isClosedOut` is the organiser saying "the door is shut, this is the final
   attendance". It is what separates a registrant who has not arrived yet from
   one who never came, so no-show is only ever derived from a closed-out event.
   Archiving hides an event from the lists without dropping its attendance,
   which every member's event history is counted from.

   `host` is the company putting the event on, and a themed social has none.

   `isMembersOnly` is the door policy: most events accept members of the
   community only, and a few, like the singles evenings, accept anyone. It
   warns the organiser at the door and never refuses anybody, because the
   person standing there is the one who decides.

   `id` is generated by this app and written into the `Event ID` cell, and
   `rowNumber` is where that cell currently is. The two are kept apart because
   only one of them survives somebody sorting the tab: the id is what every
   attendance row points at, and the row number is only ever good enough to
   address a cell in the same breath it was read. */
export type CommunityEvent = {
  rowNumber: number
  id: string
  name: string
  date: string
  host: string | undefined
  location: string
  isMembersOnly: boolean
  isClosedOut: boolean
  isArchived: boolean
}

/* An event that has been described but not yet written to a row. It already
   carries its id, because the id is what the append writes and what every
   later read finds it by; the row number is the one thing only the sheet
   knows. */
export type NewEvent = Omit<CommunityEvent, 'rowNumber'>
