import type { CommunityEvent } from './communityEvent'
import { EVENT_COLUMNS } from './eventRegistryColumns'
import { buildEventRowRange, EVENTS_HEADER_RANGE, EVENTS_TAB_NAME } from './eventRegistryTabs'
import type { SheetsClient } from '../../sheets/sheetsClient'

export type VerifiedEventRow = {
  headerRow: readonly string[]
  existingRow: readonly string[]
}

/* A row number is only true until somebody inserts, deletes or sorts a row
   above it, and the one this event carries came from a read that may be
   minutes old. A write to a stale row number edits a different event, in a tab
   where nothing would ever show that it happened.

   One field settles it, where the members path needs three: the `Event ID` is
   generated by this app and never reused, so a row that still holds it is that
   event and a row that does not is not. The header comes back in the same
   breath, so the write places its values by the layout the tab has now. */
export const readVerifiedEventRow = async ({
  sheetsClient,
  expectedEvent,
}: {
  sheetsClient: SheetsClient
  expectedEvent: CommunityEvent
}): Promise<VerifiedEventRow> => {
  const { rowNumber } = expectedEvent
  const [headerRows, eventRows] = await Promise.all([
    sheetsClient.readRange({ range: EVENTS_HEADER_RANGE }),
    sheetsClient.readRange({ range: buildEventRowRange(rowNumber) }),
  ])

  const headerRow = headerRows[0]
  if (headerRow === undefined) {
    throw new Error(
      `The ${EVENTS_TAB_NAME} tab has no header row to read \u{2014} nothing was written.`,
    )
  }

  const existingRow = eventRows[0] ?? []
  const recordedId = EVENT_COLUMNS.readCell({ headerRow, row: existingRow, target: 'id' })

  if (recordedId !== expectedEvent.id) {
    throw new Error(
      `The ${EVENTS_TAB_NAME} tab changed while you were working: row ${rowNumber} no longer holds ${expectedEvent.name}. Nothing was written \u{2014} reload the events before changing anything else.`,
    )
  }

  return { headerRow, existingRow }
}
