import type { Member } from './member'

/* Invented people. Nobody here is real; every address is @example.com. The gaps
   are deliberate: the live sheet was filled in by hand over years, so gender,
   phone, city, LinkedIn, interests, shirt size and notes are blank far more
   often than not.

   The members directory no longer uses any of this \u{2014} it reads the real
   Members tab. What is left is the cast the Events section is populated with,
   and it lives here only because Events imports it from here. Delete it with
   the last of the invented Events screens. */
export const SAMPLE_MEMBERS: readonly Member[] = [
  {
    rowNumber: 2,
    name: 'Dana Sorkin',
    company: 'Ridgeway Systems',
    title: 'Site Reliability Engineer',
    gender: 'F',
    mail: 'dana.sorkin@example.com',
    informedForMembership: 'Yes',
    phone: '050-000-0101',
    city: 'Tel Aviv',
    linkedIn: 'https://www.linkedin.com/in/dana-sorkin-example',
    interests: 'Infrastructure, Mentorship',
    shirtSize: 'M',
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-02-14',
  },
  {
    rowNumber: 3,
    name: 'Ori Weintraub',
    company: 'Palewood Analytics',
    title: 'Data Engineer',
    gender: 'M',
    mail: 'ori.weintraub@example.com',
    informedForMembership: 'Yes',
    phone: undefined,
    city: 'Haifa',
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-02-14',
  },
  {
    rowNumber: 4,
    name: 'Hila Zarnitsky',
    company: 'Brightfell Media',
    title: 'Head of Product',
    gender: 'F',
    mail: 'hila.zarnitsky@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: 'https://www.linkedin.com/in/hila-zarnitsky-example',
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-03-02',
  },
  {
    rowNumber: 5,
    name: '\u{05E8}\u{05E2}\u{05D5}\u{05EA} \u{05D2}\u{05DC}\u{05D1}\u{05E8}\u{05D3}',
    company: 'Cobalt Harbor',
    title: 'Engineering Manager',
    gender: 'F',
    mail: 'reut.gelbard@example.com',
    informedForMembership: 'Yes',
    phone: '050-000-0105',
    city: 'Ramat Gan',
    linkedIn: undefined,
    interests: 'Leadership',
    shirtSize: 'S',
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-03-02',
  },
  {
    rowNumber: 6,
    name: 'Tomer Reznik',
    company: 'Halcyon Mobility',
    title: 'iOS Developer',
    gender: 'M',
    mail: 'tomer.reznik@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: undefined,
  },
  {
    rowNumber: 7,
    name: 'Shani Oberman',
    company: 'Vesper Diagnostics',
    title: 'Clinical Data Manager',
    gender: undefined,
    mail: 'shani.oberman@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: 'Jerusalem',
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-06-19',
  },
  {
    rowNumber: 8,
    name: 'Amit Shtulman',
    company: 'Ridgeway Systems',
    title: 'Support Engineer',
    gender: undefined,
    mail: 'amit.shtulman@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-06-19',
  },
  {
    rowNumber: 9,
    name: 'Noga Feldbaum',
    company: 'Thistlewood Games',
    title: 'Technical Artist',
    gender: 'F',
    mail: 'noga.feldbaum@example.com',
    informedForMembership: 'Yes, 2023-07-04',
    phone: '050-000-0109',
    city: 'Tel Aviv',
    linkedIn: 'https://www.linkedin.com/in/noga-feldbaum-example',
    interests: 'Games, Community events',
    shirtSize: 'L',
    notes: 'Offered to help run the next meetup.',
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-07-04',
  },
  {
    rowNumber: 10,
    name: 'Roni Halperin',
    company: undefined,
    title: 'Independent Security Consultant',
    gender: undefined,
    mail: 'roni.halperin@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-09-11',
  },
  {
    rowNumber: 11,
    name: 'Yael Terkel',
    company: 'Marlowe Fintech',
    title:
      'Director of Engineering, Payments Platform and Merchant Risk (Europe, Middle East and Africa)',
    gender: 'F',
    mail: 'yael.terkel@example.com',
    informedForMembership: 'Yes',
    phone: undefined,
    city: 'Herzliya',
    linkedIn: 'https://www.linkedin.com/in/yael-terkel-example',
    interests: 'Fintech, Hiring',
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2023-09-11',
  },
  {
    rowNumber: 12,
    name: 'Eden Marziano',
    company: 'Kessler and Poole',
    title: 'Legal Counsel',
    gender: undefined,
    mail: 'eden.marziano@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: undefined,
  },
  {
    rowNumber: 13,
    name: 'Liat Grunwald',
    company: 'Northgate Energy',
    title: 'Data Scientist',
    gender: 'F',
    mail: 'liat.grunwald@example.com',
    informedForMembership: 'Yes',
    phone: undefined,
    city: 'Beer Sheva',
    linkedIn: undefined,
    interests: undefined,
    shirtSize: 'M',
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2024-01-08',
  },
  {
    rowNumber: 14,
    name: 'Idan Poznansky',
    company: 'Silverbrook Systems',
    title: 'Backend Developer',
    gender: 'M',
    mail: 'idan.poznansky@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2024-01-08',
  },
  {
    rowNumber: 15,
    name: '\u{05DE}\u{05E2}\u{05D9}\u{05D9}\u{05DF} \u{05D1}\u{05E8}\u{05E7}\u{05D5}\u{05D1}\u{05D9}\u{05E5}',
    company: 'Larkspur Health',
    title: 'Product Manager',
    gender: 'F',
    mail: 'maayan.berkovitch@example.com',
    informedForMembership: 'Yes, 2024-02-19',
    phone: '050-000-0115',
    city: 'Tel Aviv',
    linkedIn: 'https://www.linkedin.com/in/maayan-berkovitch-example',
    interests: 'Health tech, Mentorship',
    shirtSize: 'S',
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2024-02-19',
  },
  {
    rowNumber: 16,
    name: 'Alon Weisbrod',
    company: 'Thornhill Robotics',
    title: 'Mechanical Engineer',
    gender: 'M',
    mail: 'alon.weisbrod@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2024-02-19',
  },
  {
    rowNumber: 17,
    name: 'Tal Hirshfeld',
    company: 'Greyloch Studios',
    title: 'QA Lead',
    gender: undefined,
    mail: 'tal.hirshfeld@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: 'Netanya',
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: 'Name spelled two ways on the old list.',
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2024-04-30',
  },
  {
    rowNumber: 18,
    name: 'Maor Yitzhaki',
    company: 'Emberline Cloud',
    title: 'Solutions Architect',
    gender: 'M',
    mail: 'maor.yitzhaki@example.com',
    informedForMembership: 'Yes',
    phone: undefined,
    city: undefined,
    linkedIn: 'https://www.linkedin.com/in/maor-yitzhaki-example',
    interests: undefined,
    shirtSize: 'XL',
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2024-04-30',
  },
  {
    rowNumber: 19,
    name: 'Sivan Kravitz',
    company: 'Dunmore Labs',
    title: 'Research Scientist',
    gender: 'F',
    mail: 'sivan.kravitz@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2024-08-06',
  },
  {
    rowNumber: 20,
    name: 'Michal Sternberg',
    company: 'Brightfell Media',
    title: 'Content Strategist',
    gender: 'F',
    mail: 'michal.sternberg@example.com',
    informedForMembership: 'Yes',
    phone: '050-000-0120',
    city: 'Tel Aviv',
    linkedIn: undefined,
    interests: 'Writing',
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2024-08-06',
  },
  {
    rowNumber: 21,
    name: 'Yuval Ardon',
    company: 'Cobalt Harbor',
    title: 'Junior Frontend Developer',
    gender: undefined,
    mail: 'yuval.ardon@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2025-01-21',
  },
  {
    rowNumber: 22,
    name: 'Keren Mizrachi',
    company: 'Halcyon Mobility',
    title: undefined,
    gender: 'F',
    mail: 'keren.mizrachi@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Active',
    removalReason: undefined,
    approvedAt: '2025-01-21',
  },
  {
    rowNumber: 23,
    name: 'Gaya Ronen',
    company: 'Wexford Analytics',
    title: 'Analytics Lead',
    gender: undefined,
    mail: 'gaya.ronen@example.com',
    informedForMembership: 'Yes',
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Ex-member',
    removalReason: 'Moved abroad',
    approvedAt: '2023-03-02',
  },
  {
    rowNumber: 24,
    name: 'Nir Glazerman',
    company: 'Fairhaven Logistics',
    title: 'Operations Manager',
    gender: 'M',
    mail: 'nir.glazerman@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: 'Haifa',
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Ex-member',
    removalReason: 'Left tech',
    approvedAt: '2023-06-19',
  },
  {
    rowNumber: 25,
    name: 'Efrat Bilkis',
    company: 'Sandalwood Design',
    title: 'UX Researcher',
    gender: 'F',
    mail: 'efrat.bilkis@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: 'Asked to come off the mailing list as well.',
    status: 'Ex-member',
    removalReason: 'Requested removal',
    approvedAt: '2023-09-11',
  },
  {
    rowNumber: 26,
    name: 'Doron Szabo',
    company: 'Oakmere Security',
    title: 'Penetration Tester',
    gender: 'M',
    mail: 'doron.szabo@example.com',
    informedForMembership: undefined,
    phone: undefined,
    city: undefined,
    linkedIn: undefined,
    interests: undefined,
    shirtSize: undefined,
    notes: undefined,
    status: 'Ex-member',
    removalReason: 'Code of conduct',
    approvedAt: '2024-01-08',
  },
]
